---
  - name: install filebeat and metricbeat
    hosts: test
    become: true
    tasks:
        - name: download metric
          command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb
        - name: Install deb file
          command: dpkg -i metricbeat-7.4.0-amd64.deb
        - name: copy metricbeat config
          copy:
            src: /etc/ansible/metric-config.yml
            dest: /etc/metricbeat/metricbeat.yml
        - name: run metricbeat docker_container
          command: metricbeat modules enable docker
        - name: metricbeat setup
          command: metricbeat setup
        - name: metricbeat -e
          command: service metricbeat start
        - name: systemd metricbeat
          systemd:
            name: metricbeat
            enabled: yes
